INSERT INTO TEST_USER (USERNAME, PASSWORD) VALUES ('admin', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO TEST_USER (USERNAME, PASSWORD) VALUES ('user', '$2a$12$adSNSXnjb3ftqzw/kJnBlOGKrWJuL8NeYrVEnXYBjoxFkSIVYZSDi');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');