CREATE TABLE TEST_USER (
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(256) NOT NULL,
  ACCOUNT_NON_LOCKED VARCHAR(10) DEFAULT 'true',
  FAILED_ATTEMPT INT DEFAULT 0,
  LOCK_TIME DATE NULL
);

CREATE TABLE AUTH_USER_GROUP (
  AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL,
  AUTH_GROUP VARCHAR(128) NOT NULL,
  CONSTRAINT USER_AUTH_USER_GROUP_FK FOREIGN KEY(USERNAME) REFERENCES TEST_USER(USERNAME),
  UNIQUE (USERNAME, AUTH_GROUP)
);

CREATE TABLE SECRET (
  SECRET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SECRET_LINK VARCHAR(256) NOT NULL,
  SECRET_DATA VARCHAR(1000) NOT NULL,
  VIEWED BOOLEAN NOT NULL
);